In [1]:
import pandas as pd
import random

In [2]:
tickets = pd.read_csv("tickets.csv",sep=",")

In [3]:
tickets

                                          Address Ticket_Numb
0    21o3boLec9QyUhwLEJECE97bK4i5pza8CpxpRBcYEAAp    ticket#0
1    21o3boLec9QyUhwLEJECE97bK4i5pza8CpxpRBcYEAAp    ticket#1
2    21o3boLec9QyUhwLEJECE97bK4i5pza8CpxpRBcYEAAp    ticket#2
3    21o3boLec9QyUhwLEJECE97bK4i5pza8CpxpRBcYEAAp    ticket#3
4    21o3boLec9QyUhwLEJECE97bK4i5pza8CpxpRBcYEAAp    ticket#4
..                                            ...         ...
417   RCXtWdNWQnHwBubsuEGh9w4ZsmWqa4XUPyZVuEZYKhh  ticket#417
418   YZJ4nCdAum44Th2GPreCiZLaFKYkQtz6Hwvig5Eiq9p  ticket#418
419   YZJ4nCdAum44Th2GPreCiZLaFKYkQtz6Hwvig5Eiq9p  ticket#419
420   YZJ4nCdAum44Th2GPreCiZLaFKYkQtz6Hwvig5Eiq9p  ticket#420
421   YZJ4nCdAum44Th2GPreCiZLaFKYkQtz6Hwvig5Eiq9p  ticket#421

[422 rows x 2 columns]

In [4]:
total_ticket = len(tickets)
total_ticket

422

# Rewards
- 200 X WWV Cowgirl NFT
- 10 x WWV Cowboy NFT
- 0.5 SOL X 10 Winners 
- 0.25 SOL X 20 Winners
- 0.1 SOL X 25 Winners

# Choose 265 ticket number:
From the list:
- first 200 winner ticket will get Cowgirl NFT
- following 10 winner ticket will get Cowboy NFT
- following 10 winner ticket will get 0.5 SOL
- following 20 winner ticket will get 0.25 SOL
- following 25 winner ticket will get 0.1 SOL

In [5]:
all_winners = random.sample(range(total_ticket), 265)

In [6]:
all_winners

[330,
 340,
 386,
 221,
 180,
 82,
 212,
 95,
 86,
 100,
 286,
 31,
 65,
 381,
 229,
 13,
 243,
 314,
 295,
 344,
 20,
 191,
 335,
 417,
 34,
 1,
 401,
 241,
 215,
 323,
 129,
 301,
 11,
 270,
 246,
 375,
 312,
 130,
 123,
 193,
 37,
 385,
 325,
 36,
 392,
 208,
 9,
 206,
 382,
 22,
 184,
 182,
 137,
 188,
 362,
 398,
 357,
 249,
 272,
 186,
 156,
 298,
 147,
 60,
 75,
 51,
 198,
 159,
 416,
 259,
 238,
 14,
 71,
 296,
 185,
 254,
 394,
 262,
 280,
 305,
 217,
 320,
 151,
 85,
 383,
 420,
 281,
 256,
 47,
 337,
 232,
 355,
 413,
 289,
 155,
 210,
 371,
 21,
 380,
 345,
 6,
 181,
 306,
 105,
 32,
 372,
 189,
 169,
 390,
 331,
 99,
 183,
 213,
 106,
 299,
 261,
 115,
 28,
 358,
 195,
 172,
 418,
 277,
 170,
 33,
 235,
 113,
 149,
 351,
 407,
 354,
 87,
 97,
 283,
 341,
 411,
 297,
 77,
 157,
 64,
 266,
 379,
 174,
 324,
 326,
 365,
 135,
 349,
 25,
 139,
 260,
 322,
 384,
 350,
 26,
 12,
 73,
 96,
 415,
 233,
 48,
 327,
 15,
 150,
 377,
 136,
 267,
 91,
 236,
 92,
 117,
 201,
 161,
 173,
 399,
 101,
 38,
 0,
 332,
 360,
 80,
 69,
 171,
 276,
 317,
 223,
 230,
 404,
 109,
 216,
 396,
 214,
 2,
 247,
 194,
 234,
 19,
 395,
 378,
 336,
 200,
 166,
 348,
 287,
 68,
 274,
 403,
 146,
 90,
 107,
 177,
 264,
 257,
 120,
 409,
 16,
 40,
 248,
 225,
 53,
 321,
 17,
 143,
 252,
 352,
 209,
 310,
 408,
 376,
 5,
 153,
 114,
 318,
 199,
 45,
 240,
 158,
 3,
 219,
 163,
 292,
 202,
 112,
 245,
 41,
 72,
 237,
 10,
 346,
 329,
 268,
 218,
 231,
 165,
 197,
 35,
 205,
 333,
 55,
 339,
 178,
 196,
 192,
 74,
 132]

In [7]:
cowgirl_winner_tickets = all_winners[0:200]
cowgirl_winner_tickets

[330,
 340,
 386,
 221,
 180,
 82,
 212,
 95,
 86,
 100,
 286,
 31,
 65,
 381,
 229,
 13,
 243,
 314,
 295,
 344,
 20,
 191,
 335,
 417,
 34,
 1,
 401,
 241,
 215,
 323,
 129,
 301,
 11,
 270,
 246,
 375,
 312,
 130,
 123,
 193,
 37,
 385,
 325,
 36,
 392,
 208,
 9,
 206,
 382,
 22,
 184,
 182,
 137,
 188,
 362,
 398,
 357,
 249,
 272,
 186,
 156,
 298,
 147,
 60,
 75,
 51,
 198,
 159,
 416,
 259,
 238,
 14,
 71,
 296,
 185,
 254,
 394,
 262,
 280,
 305,
 217,
 320,
 151,
 85,
 383,
 420,
 281,
 256,
 47,
 337,
 232,
 355,
 413,
 289,
 155,
 210,
 371,
 21,
 380,
 345,
 6,
 181,
 306,
 105,
 32,
 372,
 189,
 169,
 390,
 331,
 99,
 183,
 213,
 106,
 299,
 261,
 115,
 28,
 358,
 195,
 172,
 418,
 277,
 170,
 33,
 235,
 113,
 149,
 351,
 407,
 354,
 87,
 97,
 283,
 341,
 411,
 297,
 77,
 157,
 64,
 266,
 379,
 174,
 324,
 326,
 365,
 135,
 349,
 25,
 139,
 260,
 322,
 384,
 350,
 26,
 12,
 73,
 96,
 415,
 233,
 48,
 327,
 15,
 150,
 377,
 136,
 267,
 91,
 236,
 92,
 117,
 201,
 161,
 173,
 399,
 101,
 38,
 0,
 332,
 360,
 80,
 69,
 171,
 276,
 317,
 223,
 230,
 404,
 109,
 216,
 396,
 214,
 2,
 247,
 194,
 234,
 19,
 395,
 378,
 336]

In [8]:
textfile = open("cowgirl_winner.txt", "w")
for element in cowgirl_winner_tickets:
    textfile.write(str(element) + "\n")
textfile.close()

In [9]:
cowboy_winner_tickets = all_winners[200:210]
cowboy_winner_tickets

[200, 166, 348, 287, 68, 274, 403, 146, 90, 107]

In [10]:
textfile = open("cowboy_winner.txt", "w")
for element in cowboy_winner_tickets:
    textfile.write(str(element) + "\n")
textfile.close()

In [11]:
sol_05_winner_tickets = all_winners[210:220]
sol_05_winner_tickets

[177, 264, 257, 120, 409, 16, 40, 248, 225, 53]

In [12]:
textfile = open("sol_05_winner.txt", "w")
for element in sol_05_winner_tickets:
    textfile.write(str(element) + "\n")
textfile.close()

In [13]:
sol_025_winner_tickets = all_winners[220:240]
sol_025_winner_tickets

[321,
 17,
 143,
 252,
 352,
 209,
 310,
 408,
 376,
 5,
 153,
 114,
 318,
 199,
 45,
 240,
 158,
 3,
 219,
 163]

In [14]:
textfile = open("sol_025_winner.txt", "w")
for element in sol_025_winner_tickets:
    textfile.write(str(element) + "\n")
textfile.close()

In [15]:
sol_01_winner_tickets = all_winners[240:265]
sol_01_winner_tickets

[292,
 202,
 112,
 245,
 41,
 72,
 237,
 10,
 346,
 329,
 268,
 218,
 231,
 165,
 197,
 35,
 205,
 333,
 55,
 339,
 178,
 196,
 192,
 74,
 132]

In [16]:
textfile = open("sol_01_winner.txt", "w")
for element in sol_01_winner_tickets:
    textfile.write(str(element) + "\n")
textfile.close()